export const brands = [
  { label: "States Brand", key: "states-brand" },
  { label: "Mexico Brand", key: "mexico-brand" },
  { label: "Sun Brand", key: "sun-brand" },
  { label: "Moon Brand", key: "moon-brand" },
  { label: "Super Brand", key: "super-brand" },
];



export const countries = [
  { label: "Mexico", key: "mexico" },
  { label: "United States", key: "united-states" },
  { label: "Thailand", key: "thailand" },
  { label: "China", key: "china" },
  { label: "Jamaica", key: "jamaica" },
  { label: "South Korea", key: "south-korea" },
  { label: "India", key: "india" },
  { label: "Malaysia", key: "malaysia" },
  { label: "Indonesia", key: "indonesia" },
  { label: "Trinidad and Tobago", key: "trinidad-and-tobago" },
  { label: "Vietnam", key: "vietnam" },
  { label: "Sri Lanka", key: "sri-lanka" },
  { label: "Peru", key: "peru" },
  { label: "Brazil", key: "brazil" },
  { label: "Hungary", key: "hungary" },
  { label: "Japan", key: "japan" },
  { label: "Singapore", key: "singapore" },
  { label: "Belize", key: "belize" },
  { label: "Ghana", key: "ghana" },
  { label: "Nigeria", key: "nigeria" },
  { label: "Philippines", key: "philippines" },
  { label: "Cambodia", key: "cambodia" },
  { label: "Morocco", key: "morocco" },
  { label: "Tunisia", key: "tunisia" },
  { label: "Ethiopia", key: "ethiopia" },
  { label: "Myanmar", key: "myanmar" },
  { label: "Laos", key: "laos" },
  { label: "Spain", key: "spain" },
  { label: "Italy", key: "italy" },
  { label: "Turkey", key: "turkey" },
  { label: "Portugal", key: "portugal" },
  { label: "South Africa", key: "south-africa" },
  { label: "Zimbabwe", key: "zimbabwe" },
  { label: "Kenya", key: "kenya" },
  { label: "Uganda", key: "uganda" },
  { label: "Barbados", key: "barbados" },
  { label: "Grenada", key: "grenada" },
  { label: "Haiti", key: "haiti" },
  { label: "Dominican Republic", key: "dominican-republic" },
  { label: "Costa Rica", key: "costa-rica" },
  { label: "Panama", key: "panama" },
  { label: "Colombia", key: "colombia" },
  { label: "Ecuador", key: "ecuador" },
  { label: "Bolivia", key: "bolivia" },
  { label: "Argentina", key: "argentina" },
  { label: "Chile", key: "chile" },
  { label: "Bhutan", key: "bhutan" },
  { label: "Nepal", key: "nepal" },
  { label: "Bangladesh", key: "bangladesh" },
  { label: "Taiwan", key: "taiwan" }
];


